"use client";
import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/api';

const plans = [
  ['Individual Retainer', '1 year', '30% professional fee discount'], ['Biz-Pro Retainer', '1 year', '50% professional fee discount'], ['Big Daddy / Big Mummy Group', '2 years', 'Family and initiator business cover'], ['SME Group Retainer', '1 year', 'Owners and up to 10 staff'], ['Comprehensive Family', '3 years', 'Family lawyer and quarterly interphase'], ['Comprehensive Corporate', '5 years', 'Corporate advisory and secretarial support'], ['Premium Life', '10 years', 'Long-term personal, family and corporate cover'], ['Equity Premium', 'Perpetual option', '10% equity allocation for eligible start-ups'],
];

export default function GeneralRetainerOverview() {
  const [claims, setClaims] = useState<any[]>([]); const [payments, setPayments] = useState<any[]>([]);
  useEffect(() => { Promise.all([apiFetch('/cases/my-cases').catch(() => []), apiFetch('/payments/my-payments').catch(() => [])]).then(([caseData, paymentData]) => { setClaims(Array.isArray(caseData) ? caseData.filter((item) => item.category !== 'LITIGATION') : []); setPayments(Array.isArray(paymentData) ? paymentData : []); }); }, []);
  const openClaims = claims.filter((item) => !['CLOSED', 'RESOLVED', 'COMPLETED'].includes(String(item.status || '').toUpperCase())).length;
  return <div className="space-y-8">
    <section className="rounded-[32px] bg-gradient-to-br from-[#173d27] via-[#1f5b37] to-[#a87835] p-8 text-white shadow-xl"><span className="rounded-full border border-amber-200/40 bg-amber-100/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.2em] text-amber-100">Midlex Royalty</span><h1 className="mt-4 text-3xl font-black">General Retainer Portal</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/80">Review retainer plans, manage general claims and monitor client payments in the General workspace.</p><div className="mt-6 rounded-2xl border border-amber-100/20 bg-white/10 p-4 text-xs leading-5 text-amber-50">Coverage begins after payment and the executed Retainer Client onboarding form. Brochure pricing is indicative and final terms are governed by the signed retainer arrangement.</div><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard/cases/new?category=GENERAL&subCategory=General%20Legal%20Advisory" className="rounded-xl bg-amber-400 px-5 py-3 text-xs font-black uppercase tracking-wider text-[#173d27]">Submit retainer claim</Link><Link href="/dashboard/payments" className="rounded-xl border border-white/30 bg-white/10 px-5 py-3 text-xs font-black uppercase tracking-wider text-white">View payments</Link></div></section>
    <div className="grid gap-4 sm:grid-cols-3">{[['Claims', claims.length], ['Open claims', openClaims], ['Payments', payments.length]].map(([label, value]) => <div key={String(label)} className="rounded-3xl border border-amber-100 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-gray-400">{label}</p><p className="mt-3 text-3xl font-black text-[#173d27]">{value}</p></div>)}</div>
    <section className="rounded-[32px] border border-gray-100 bg-white p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#a87835]">Retainer catalogue</p><h2 className="mt-2 text-2xl font-black text-[#173d27]">Plans available to clients</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => <div key={plan[0]} className="rounded-2xl border border-gray-100 p-5"><h3 className="font-black text-[#173d27]">{plan[0]}</h3><p className="mt-2 text-xs font-bold text-[#a87835]">{plan[1]}</p><p className="mt-3 text-xs leading-5 text-gray-500">{plan[2]}</p></div>)}</div></section>
    <section className="rounded-[32px] border border-gray-100 bg-white p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#a87835]">Client activity</p><h2 className="mt-2 text-2xl font-black text-[#173d27]">General retainer claims</h2></div><Link href="/dashboard/cases/new?category=GENERAL&subCategory=General%20Legal%20Advisory" className="rounded-xl bg-[#173d27] px-4 py-3 text-xs font-black uppercase tracking-wider text-white">New claim</Link></div><div className="mt-6 space-y-3">{claims.length ? claims.slice(0, 5).map((item) => <Link href={`/dashboard/cases/${item.id}`} key={item.id} className="flex items-center justify-between gap-3 rounded-2xl border border-gray-100 p-4 hover:border-amber-300"><span className="font-bold text-[#173d27]">{item.title || 'General legal request'}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-[10px] font-black uppercase text-[#8a6428]">{item.status || 'Pending'}</span></Link>) : <p className="rounded-2xl border border-dashed border-gray-200 p-8 text-center text-sm text-gray-500">No general retainer claims yet.</p>}</div></section>
  </div>;
}
