"use client";

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { API_URL } from '@/lib/api';

export default function RealtyAdminLogin() {
  const router = useRouter();
  const [form, setForm] = useState({ email: '', password: '' });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${API_URL}/auth/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data?.message || 'Sign in failed'); if (data.user?.role !== 'ADMIN') throw new Error('This portal is restricted to Midlex administrators.'); localStorage.setItem('midlex_realty_admin_token', data.access_token); localStorage.setItem('midlex_realty_admin_user', JSON.stringify(data.user)); router.push('/admin'); } catch (err) { setError(err instanceof Error ? err.message : 'Sign in failed'); } finally { setLoading(false); } };
  return <main className="grid min-h-screen bg-[#fffdf7] lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-[#073d22] lg:block"><img src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=88" alt="Realty administration" className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 bg-gradient-to-br from-[#042d1a] via-[#073d22]/90 to-transparent" /><div className="relative flex h-full flex-col justify-between p-14 text-white"><Image src="/midlex-logo.png" alt="Midlex" width={190} height={70} className="h-16 w-auto rounded-xl bg-white object-contain p-2" /><div><span className="inline-flex items-center gap-2 rounded-full border border-[#ddb849]/40 bg-[#ddb849]/10 px-4 py-2 text-xs font-black uppercase tracking-widest text-[#ddb849]"><ShieldCheck size={16} /> Secure administration</span><h1 className="mt-6 max-w-lg text-5xl font-black leading-tight">Manage the Midlex property marketplace.</h1><p className="mt-5 max-w-lg leading-7 text-emerald-100/70">Publish listings, update availability, feature priority properties, manage galleries and receive buyer enquiries.</p></div><p className="text-xs text-emerald-100/45">Midlex Realty administrative access</p></div></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-md"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={17} /> Back to marketplace</Link><div className="mt-10 lg:hidden"><Image src="/midlex-logo.png" alt="Midlex" width={170} height={60} className="h-14 w-auto object-contain" /></div><p className="mt-10 text-xs font-black uppercase tracking-[.2em] text-[#a87835]">Realty administration</p><h2 className="mt-2 text-4xl font-black text-[#073d22]">Admin sign in</h2><p className="mt-3 text-sm leading-6 text-slate-500">Use an authorised Midlex administrator account.</p><form onSubmit={submit} className="mt-8 space-y-4"><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4"><Mail size={18} className="text-[#a87835]" /><input required type="email" placeholder="Admin email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className="w-full border-0 py-4 text-sm outline-none" /></label><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4"><LockKeyhole size={18} className="text-[#a87835]" /><input required type="password" placeholder="Password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} className="w-full border-0 py-4 text-sm outline-none" /></label>{error && <p className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#073d22] p-4 text-sm font-black text-white shadow-lg disabled:opacity-50">{loading ? 'Signing in...' : 'Sign in to Realty admin'}</button></form></div></section></main>;
}
